# Generated by Django 3.2 on 2021-04-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooom',
            new_name='Room',
        ),
    ]
