# Generated by Django 3.2 on 2021-04-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_rooom_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_can_skip',
            new_name='votes_to_skip',
        ),
    ]
